# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200408_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image_url',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片路径'),
        ),
    ]
